permalink:           date

# Setup
title:               Anantha Kumaran
tagline:             'random thoughts'
description:         'Random thoughts of a programmer.'
url:                 http://ananthakumaran.in
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Anantha Kumaran
  url:               http://ananthakumaran.in
  email:             ananthakumaran@gmail.com

# Custom vars
version:             1.0.0

highlighter:         rouge
# lsi:                 false
# safe:                true
excerpt_separator:   ""

gems:
  - jekyll-paginate
  - jekyll-sitemap
